export const config = {
  readonly: false,
  height: 300,
  placeholder: "Olá mundo",
  style: {
    font: "16px Roboto",
  },
  tabIndex: 1,
  toolbarAdaptive: true,
  toolbarButtonSize: "middle",
  toolbarInline: true,
  removeButtons: [
    "strikethrough",
    "eraser",
    "font",
    "fontsize",
    "classSpan",
    "lineHeight",
    "superscript",
    "subscript",
    "file",
    "image",
    "video",
    "cut",
    "copy",
    "paste",
    "selectall",
    "copyformat",
    "table",
    "link",
    "symbols",
    "indent",
    "outdent",
    "left",
    "brush",
    "find",
    "source",
    "print",
    "about",
  ],
};
